// -----------------------------------------------------------------------------
// @generated by xtask/codegen (signed)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

#[test]
fn try_from_ops_range_converts_half_open_range() {
    let r = -5..10i64;
    let iv = I64CO::try_from(r).unwrap();
    assert_eq!(iv.start(), -5);
    assert_eq!(iv.end_excl(), 10);
}

#[test]
fn try_from_ops_range_rejects_empty_range() {
    assert!(I64CO::try_from(3i64..3).is_err());
}

#[test]
fn try_from_ops_range_rejects_reversed_range() {
    assert!(I64CO::try_from(10i64..-5).is_err());
}
