mod signed;
mod unsigned;

use std::{
    env, fs,
    path::{Path, PathBuf},
};

const UNSIGNED_TYPES: &[(&str, &str)] = &[
    ("u16", "U16CO"),
    ("u32", "U32CO"),
    ("u64", "U64CO"),
    ("u128", "U128CO"),
    ("usize", "UsizeCO"),
];

const SIGNED_TYPES: &[(&str, &str)] = &[
    ("i16", "I16CO"),
    ("i32", "I32CO"),
    ("i64", "I64CO"),
    ("i128", "I128CO"),
    ("isize", "IsizeCO"),
];

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum EmitMode {
    Write,
    Check,
}

impl EmitMode {
    #[inline]
    fn is_check(self) -> bool {
        matches!(self, Self::Check)
    }
}

fn main() {
    let mut args = env::args().skip(1);

    let mode = args.next().unwrap_or_else(|| {
        panic!("missing mode, expected one of: `signed`, `unsigned`, `all`, `check`")
    });

    let mut emit = EmitMode::Write;

    let target = match mode.as_str() {
        "signed" | "unsigned" | "all" => mode.as_str(),
        "check" => {
            emit = EmitMode::Check;
            "all"
        }
        other => panic!(
            "unsupported mode: {other}, expected one of: `signed`, `unsigned`, `all`, `check`"
        ),
    };

    for arg in args {
        match arg.as_str() {
            "--check" | "check" => emit = EmitMode::Check,
            other => panic!("unsupported arg: {other}, expected `--check`"),
        }
    }

    let root = workspace_root();
    let src = root.join("src").join("interval");

    match target {
        "signed" => signed::generate(&src, emit),
        "unsigned" => unsigned::generate(&src, emit),
        "all" => {
            signed::generate(&src, emit);
            unsigned::generate(&src, emit);
        }
        _ => unreachable!(),
    }

    write_interval_mod(&src, emit);

    if emit.is_check() {
        eprintln!("codegen check passed");
    }
}

/// workspace root
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent() // xtask
        .unwrap()
        .parent() // workspace root
        .unwrap()
        .to_path_buf()
}

pub(crate) fn emit_file(path: impl AsRef<Path>, expected: String, mode: EmitMode) {
    let path = path.as_ref();

    match mode {
        EmitMode::Write => {
            fs::write(path, expected).unwrap();
        }
        EmitMode::Check => {
            let actual = fs::read_to_string(path).unwrap_or_else(|err| {
                panic!(
                    "generated file is missing or unreadable: {}\nerror: {err}",
                    path.display()
                )
            });

            if actual != expected {
                panic!(
                    "generated file is stale: {}\nrun codegen and commit the updated output",
                    path.display()
                );
            }
        }
    }
}

fn write_interval_mod(src: &Path, mode: EmitMode) {
    let mut s = String::new();

    // This file is generated by xtask/codegen.
    // The #[cfg(test)] mod tests_for_adversarial declaration at the end is
    // intentionally kept here — do not remove it from the generator.
    s.push_str(
        "// -----------------------------------------------------------------------------\n",
    );
    s.push_str("// @generated by xtask/codegen\n");
    s.push_str("// DO NOT EDIT MANUALLY.\n");
    s.push_str("// Changes will be overwritten.\n");
    s.push_str(
        "// -----------------------------------------------------------------------------\n\n",
    );

    // Mod declarations — cargo fmt sorts alphabetically (string order).
    // Collect all type module names, add res + traits, sort, emit.
    let mut mod_names: Vec<String> = vec!["res".into(), "traits".into()];
    for (ty, _) in SIGNED_TYPES.iter().chain(UNSIGNED_TYPES) {
        mod_names.push(ty.to_string());
    }
    mod_names.push("i8".into());
    mod_names.push("u8".into());
    mod_names.sort();

    for name in &mod_names {
        match name.as_str() {
            "traits" => s.push_str("pub mod traits;\n"),
            _ => s.push_str(&format!("mod {name};\n")),
        }
    }
    s.push('\n');

    // Re-exports — cargo fmt groups by prefix (i, res, u), numeric
    // sort within each group: i8, i16, i32, i64, i128, isize, res,
    // u8, u16, u32, u64, u128, usize.
    s.push_str("pub use i8::I8CO;\n");
    for (ty, name) in SIGNED_TYPES {
        s.push_str(&format!("pub use {ty}::{name};\n"));
    }
    s.push_str("pub use res::{EmptyRangeError, OneTwo, ZeroOneTwo};\n");
    s.push_str("pub use u8::U8CO;\n");
    for (ty, name) in UNSIGNED_TYPES {
        s.push_str(&format!("pub use {ty}::{name};\n"));
    }
    s.push('\n');
    s.push_str("#[cfg(test)]\n");
    s.push_str("mod tests_for_adversarial;\n");

    emit_file(src.join("..").join("interval.rs"), s, mode);
}
