use std::{fs, path::Path};

use crate::{EmitMode, emit_file};

const GENERATED_WARNING: &str = "\
// -----------------------------------------------------------------------------\n\
// @generated by xtask/codegen (signed)\n\
// DO NOT EDIT MANUALLY.\n\
// Changes will be overwritten.\n\
// -----------------------------------------------------------------------------\n\n";

/// (signed_primitive_type, struct_name, unsigned_peer_type)
const TYPES: &[(&str, &str, &str)] = &[
    ("i16", "I16CO", "u16"),
    ("i32", "I32CO", "u32"),
    ("i64", "I64CO", "u64"),
    ("i128", "I128CO", "u128"),
    ("isize", "IsizeCO", "usize"),
];

const TEMPLATE_FILE: &str = "i8.rs";
const TEMPLATE_TY: &str = "i8";
const TEMPLATE_NAME: &str = "I8CO";
const TEMPLATE_LEN_TY: &str = "u8";

pub fn generate(src: &Path, mode: EmitMode) {
    let template = fs::read_to_string(src.join(TEMPLATE_FILE)).unwrap();

    for (dst_ty, dst_name, dst_len_ty) in TYPES {
        generate_type(src, &template, dst_ty, dst_name, dst_len_ty, mode);
        generate_tests(src, dst_ty, dst_name, dst_len_ty, mode);
    }
}

fn generate_type(
    src: &Path,
    template: &str,
    dst_ty: &str,
    dst_name: &str,
    dst_len_ty: &str,
    mode: EmitMode,
) {
    let body = replace_signed(template, dst_ty, dst_name, dst_len_ty);
    let code = format!("{GENERATED_WARNING}{body}");
    emit_file(src.join(format!("{dst_ty}.rs")), code, mode);
}

fn generate_tests(src: &Path, dst_ty: &str, dst_name: &str, dst_len_ty: &str, mode: EmitMode) {
    let src_tests = src.join(TEMPLATE_TY);
    let dst_tests = src.join(dst_ty);

    if !mode.is_check() {
        if dst_tests.exists() {
            fs::remove_dir_all(&dst_tests).unwrap();
        }
        fs::create_dir_all(&dst_tests).unwrap();
    }

    for entry in fs::read_dir(src_tests).unwrap() {
        let path = entry.unwrap().path();
        let text = fs::read_to_string(&path).unwrap();
        let body = replace_signed(&text, dst_ty, dst_name, dst_len_ty);
        let code = format!("{GENERATED_WARNING}{body}");

        emit_file(dst_tests.join(path.file_name().unwrap()), code, mode);
    }
}

fn replace_signed(text: &str, dst_ty: &str, dst_name: &str, dst_len_ty: &str) -> String {
    text.replace(TEMPLATE_NAME, dst_name)
        .replace(TEMPLATE_TY, dst_ty)
        .replace(TEMPLATE_LEN_TY, dst_len_ty)
}
