use std::{fs, path::Path};

use crate::{EmitMode, emit_file};

const GENERATED_WARNING: &str = "\
// -----------------------------------------------------------------------------\n\
// @generated by xtask/codegen (unsigned)\n\
// DO NOT EDIT MANUALLY.\n\
// Changes will be overwritten.\n\
// -----------------------------------------------------------------------------\n\n";

/// (primitive_type, struct_name)
const TYPES: &[(&str, &str)] = &[
    ("u16", "U16CO"),
    ("u32", "U32CO"),
    ("u64", "U64CO"),
    ("u128", "U128CO"),
    ("usize", "UsizeCO"),
];

const TEMPLATE_FILE: &str = "u8.rs";
const TEMPLATE_TY: &str = "u8";
const TEMPLATE_NAME: &str = "U8CO";

pub fn generate(src: &Path, mode: EmitMode) {
    let template = fs::read_to_string(src.join(TEMPLATE_FILE)).unwrap();

    for (dst_ty, dst_name) in TYPES {
        generate_type(src, &template, dst_ty, dst_name, mode);
        generate_tests(src, dst_ty, dst_name, mode);
    }
}

fn generate_type(src: &Path, template: &str, dst_ty: &str, dst_name: &str, mode: EmitMode) {
    let body = replace_unsigned(template, dst_ty, dst_name);
    let code = format!("{GENERATED_WARNING}{body}");
    emit_file(src.join(format!("{dst_ty}.rs")), code, mode);
}

fn generate_tests(src: &Path, dst_ty: &str, dst_name: &str, mode: EmitMode) {
    let src_tests = src.join(TEMPLATE_TY);
    let dst_tests = src.join(dst_ty);

    if !mode.is_check() {
        if dst_tests.exists() {
            fs::remove_dir_all(&dst_tests).unwrap();
        }
        fs::create_dir_all(&dst_tests).unwrap();
    }

    for entry in fs::read_dir(src_tests).unwrap() {
        let path = entry.unwrap().path();
        let text = fs::read_to_string(&path).unwrap();
        let body = replace_unsigned(&text, dst_ty, dst_name);
        let code = format!("{GENERATED_WARNING}{body}");

        emit_file(dst_tests.join(path.file_name().unwrap()), code, mode);
    }
}

fn replace_unsigned(text: &str, dst_ty: &str, dst_name: &str) -> String {
    text.replace(TEMPLATE_NAME, dst_name)
        .replace(TEMPLATE_TY, dst_ty)
}
