// -----------------------------------------------------------------------------
// @generated by xtask/codegen (unsigned)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

#[test]
fn try_from_ops_range_converts_half_open_range() {
    let r = 1..10usize;
    let iv = UsizeCO::try_from(r).unwrap();
    assert_eq!(iv.start(), 1);
    assert_eq!(iv.end_excl(), 10);
}

#[test]
fn try_from_ops_range_rejects_empty_range() {
    assert!(UsizeCO::try_from(5usize..5).is_err());
}

#[test]
fn try_from_ops_range_rejects_reversed_range() {
    assert!(UsizeCO::try_from(10usize..5).is_err());
}
