// -----------------------------------------------------------------------------
// @generated by xtask/codegen (unsigned)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

mod unit_tests {
    use super::*;

    fn span(lo: u128, hi: u128) -> U128CO {
        U128CO::try_new(lo, hi).unwrap()
    }

    #[test]
    fn midpoint_basic() {
        let iv = span(10, 20);
        assert_eq!(iv.midpoint(), 15);

        let iv2 = span(0, 2);
        assert_eq!(iv2.midpoint(), 1);

        let iv3 = span(0, u128::MAX);
        assert_eq!(iv3.midpoint(), (0 + ((u128::MAX - 0) / 2)));
    }

    #[test]
    fn checked_from_midpoint_len_basic() {
        let mid = 10;
        let len = 5;
        let iv = U128CO::checked_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        // len=0 returns None
        assert!(U128CO::checked_from_midpoint_len(mid, 0).is_none());

        // overflow start returns None
        assert!(U128CO::checked_from_midpoint_len(0, 5).is_none());

        // overflow end returns None
        assert!(U128CO::checked_from_midpoint_len(u128::MAX, 10).is_none());
    }

    #[test]
    fn saturating_from_midpoint_len_basic() {
        let mid = 10;
        let len = 5;
        let iv = U128CO::saturating_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        // len=0 returns None
        assert!(U128CO::saturating_from_midpoint_len(mid, 0).is_none());

        // saturating start
        let iv2 = U128CO::saturating_from_midpoint_len(0, 5).unwrap();
        assert_eq!(iv2.start(), 0);
        assert_eq!(iv2.len(), 5);

        // saturating end
        let iv3 = U128CO::saturating_from_midpoint_len(u128::MAX, 10).unwrap();
        assert!(iv3.end_excl() <= u128::MAX);
    }
}

mod prop_tests {
    use std::{vec, vec::Vec};

    use super::*;
    use proptest::prelude::*;

    fn edge_values() -> Vec<u128> {
        let mut v = vec![u128::MIN, u128::MAX, 0, 1];
        if u128::MIN < u128::MAX {
            v.push(u128::MIN.saturating_add(1));
            v.push(u128::MAX.saturating_sub(1));
        }
        v.sort_unstable();
        v.dedup();
        v
    }

    fn edge_scalar() -> impl Strategy<Value = u128> {
        prop::sample::select(edge_values())
    }

    fn mixed_scalar() -> impl Strategy<Value = u128> {
        prop_oneof! {
            3 => edge_scalar(),
            7 => any::<u128>(),
        }
    }

    proptest! {
        #[test]
        fn midpoint_rounds_down(x in mixed_scalar(), y in mixed_scalar()) {
            let lo = x.min(y);
            let hi = x.max(y).saturating_add(1); // ensure non-empty
            if let Some(iv) = U128CO::try_new(lo, hi) {
                let mp = iv.midpoint();
                // midpoint in interval and closer to start
                prop_assert!(mp >= iv.start() && mp <= iv.end_incl());
                prop_assert_eq!(mp, iv.start() + (iv.len() / 2));
            }
        }

        #[test]
        fn checked_from_midpoint_len_inverse(mid in mixed_scalar(), len in 1u128..20) {
            if let Some(iv) = U128CO::checked_from_midpoint_len(mid, len) {
                prop_assert_eq!(iv.len(), len);
                prop_assert_eq!(iv.midpoint(), mid);
            }
        }

        #[test]
        fn saturating_from_midpoint_len_safety(mid in mixed_scalar(), len in 1u128..20) {
            if let Some(iv) = U128CO::saturating_from_midpoint_len(mid, len) {
                // start < end_excl invariant
                prop_assert!(iv.start() < iv.end_excl());
                prop_assert_eq!(iv.midpoint(), iv.start() + (iv.len()/2));
            }
        }
    }
}
