// -----------------------------------------------------------------------------
// @generated by xtask/codegen (signed)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

const MIN: i128 = i128::MIN;
const MAX: i128 = i128::MAX;
const NEG_ONE: i128 = -1;
const ZERO: i128 = 0;
const ONE: i128 = 1;

mod unit_tests {
    use super::*;

    #[test]
    fn len_of_singleton_is_one() {
        let iv = I128CO::try_new(ZERO, ONE).unwrap();
        assert_eq!(iv.len(), 1);

        let iv = I128CO::try_new(MIN, MIN + ONE).unwrap();
        assert_eq!(iv.len(), 1);

        let iv = I128CO::try_new(MAX - ONE, MAX).unwrap();
        assert_eq!(iv.len(), 1);
    }

    #[test]
    fn len_matches_basic_examples() {
        let cases = [
            (MIN, MIN + ONE, 1),
            (MIN, MIN + 8, 8),
            (-5, ZERO, 5),
            (ZERO, ONE, 1),
            (ZERO, 10, 10),
            (5, 9, 4),
            (MAX - ONE, MAX, 1),
            (MIN, MAX, u128::MAX),
        ];

        for (start, end_excl, expect) in cases {
            let iv = I128CO::try_new(start, end_excl).unwrap();
            assert_eq!(iv.len(), expect, "case [{start}, {end_excl})");
        }
    }

    #[test]
    fn len_matches_iteration_count() {
        let cases = [
            (MIN, MIN + ONE),
            (MIN, MIN + 8),
            (-100, -90),
            (-5, ZERO),
            (NEG_ONE, ONE),
            (ZERO, ONE),
            (ZERO, 10),
            (10, 20),
            (MAX - ONE, MAX),
        ];

        for (start, end_excl) in cases {
            let iv = I128CO::try_new(start, end_excl).unwrap();
            assert_eq!(
                iv.len(),
                iv.iter().count() as u128,
                "case [{start}, {end_excl})"
            );
        }
    }

    #[test]
    fn len_equals_end_minus_start_in_order_space() {
        const SIGN_MASK: u128 = 1u128 << (i128::BITS - 1);

        let cases = [
            (MIN, MIN + ONE),
            (MIN, NEG_ONE),
            (MIN, ZERO),
            (MIN, MAX),
            (NEG_ONE, ZERO),
            (NEG_ONE, ONE),
            (ZERO, ONE),
            (ZERO, MAX),
            (MAX - ONE, MAX),
        ];

        for (start, end_excl) in cases {
            let iv = I128CO::try_new(start, end_excl).unwrap();

            let expect = ((end_excl as u128) ^ SIGN_MASK) - ((start as u128) ^ SIGN_MASK);

            assert_eq!(iv.len(), expect, "case [{start}, {end_excl})");
        }
    }

    #[test]
    fn len_is_monotonic_under_interval_extension() {
        let small = I128CO::try_new(-5, 5).unwrap();
        let large = I128CO::try_new(-10, 10).unwrap();

        assert!(small.len() < large.len());

        let small = I128CO::try_new(MIN, -120).unwrap();
        let large = I128CO::try_new(MIN, -100).unwrap();

        assert!(small.len() < large.len());

        let small = I128CO::try_new(100, 110).unwrap();
        let large = I128CO::try_new(100, MAX).unwrap();

        assert!(small.len() < large.len());
    }

    #[test]
    fn len_of_maximal_i128_interval_is_255() {
        let iv = I128CO::try_new(MIN, MAX).unwrap();
        assert_eq!(iv.len(), u128::MAX);
    }
}

mod prop_tests {
    use proptest::prelude::*;

    use super::*;

    proptest! {
        #[test]
        fn prop_len_is_positive_for_valid_intervals(start in any::<i128>(), end in any::<i128>()) {
            if let Some(iv) = I128CO::try_new(start, end) {
                prop_assert!(iv.len() >= 1);
            }
        }

        #[test]
        fn prop_len_matches_order_space_difference(start in any::<i128>(), end in any::<i128>()) {
            if let Some(iv) = I128CO::try_new(start, end) {
                const SIGN_MASK: u128 = 1u128 << (i128::BITS - 1);
                let expect = ((end as u128) ^ SIGN_MASK) - ((start as u128) ^ SIGN_MASK);
                prop_assert_eq!(iv.len(), expect);
            }
        }
    }
}
