// -----------------------------------------------------------------------------
// @generated by xtask/codegen (signed)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

mod unit_tests {
    use super::*;

    #[test]
    fn midpoint_basic() {
        let iv = I128CO::try_new(0, 5).unwrap();
        assert_eq!(iv.midpoint(), 2);

        let iv = I128CO::try_new(-5, 5).unwrap();
        assert_eq!(iv.midpoint(), 0);

        let iv = I128CO::try_new(i128::MIN, i128::MAX).unwrap();
        assert_eq!(iv.midpoint(), i128::MIN + ((iv.len() / 2) as i128));
    }

    #[test]
    fn checked_from_midpoint_len_basic() {
        let mid = 0;
        let len = 5;
        let iv = I128CO::checked_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        let mid = 10;
        let len = 4;
        let iv = I128CO::checked_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        assert!(I128CO::checked_from_midpoint_len(mid, 0).is_none());
        assert!(I128CO::checked_from_midpoint_len(i128::MIN, 10).is_none());
        assert!(I128CO::checked_from_midpoint_len(i128::MAX, 10).is_none());
    }

    #[test]
    fn saturating_from_midpoint_len_basic() {
        let mid = 0;
        let len = 5;
        let iv = I128CO::saturating_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        assert!(I128CO::saturating_from_midpoint_len(mid, 0).is_none());

        let iv = I128CO::saturating_from_midpoint_len(i128::MIN, 10).unwrap();
        assert!(iv.start() >= i128::MIN);

        let iv = I128CO::saturating_from_midpoint_len(i128::MAX, 10).unwrap();
        assert!(iv.end_excl() <= i128::MAX);
    }
}

mod prop_tests {
    use proptest::prelude::*;

    use super::*;

    fn mixed_scalar() -> impl Strategy<Value = i128> {
        prop_oneof![3 => prop::sample::select(&[i128::MIN, i128::MAX, 0, -1, 1]), 7 => any::<i128>()]
    }

    proptest! {
        #[test]
        fn prop_midpoint_in_bounds(start in any::<i128>(), end in any::<i128>()) {
            if let Some(iv) = I128CO::try_new(start, end) {
                let mp = iv.midpoint();
                prop_assert!(mp >= iv.start());
                prop_assert!(mp <= iv.end_incl());
            }
        }

        #[test]
        fn prop_checked_from_midpoint_len_inverse(mid in mixed_scalar(), len in 1u128..=255) {
            if let Some(iv) = I128CO::checked_from_midpoint_len(mid, len) {
                prop_assert_eq!(iv.len(), len);
                prop_assert_eq!(iv.midpoint(), mid);
            }
        }

        #[test]
        fn prop_saturating_from_midpoint_len_safety(mid in mixed_scalar(), len in 1u128..=255) {
            if let Some(iv) = I128CO::saturating_from_midpoint_len(mid, len) {
                prop_assert!(iv.start() < iv.end_excl());
                prop_assert_eq!(iv.midpoint(), iv.start() + (iv.len()/2) as i128);
            }
        }
    }
}
