// -----------------------------------------------------------------------------
// @generated by xtask/codegen (signed)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

mod unit_tests {
    use super::*;

    #[test]
    fn midpoint_basic() {
        let iv = IsizeCO::try_new(0, 5).unwrap();
        assert_eq!(iv.midpoint(), 2);

        let iv = IsizeCO::try_new(-5, 5).unwrap();
        assert_eq!(iv.midpoint(), 0);

        let iv = IsizeCO::try_new(isize::MIN, isize::MAX).unwrap();
        assert_eq!(iv.midpoint(), isize::MIN + ((iv.len() / 2) as isize));
    }

    #[test]
    fn checked_from_midpoint_len_basic() {
        let mid = 0;
        let len = 5;
        let iv = IsizeCO::checked_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        let mid = 10;
        let len = 4;
        let iv = IsizeCO::checked_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        assert!(IsizeCO::checked_from_midpoint_len(mid, 0).is_none());
        assert!(IsizeCO::checked_from_midpoint_len(isize::MIN, 10).is_none());
        assert!(IsizeCO::checked_from_midpoint_len(isize::MAX, 10).is_none());
    }

    #[test]
    fn saturating_from_midpoint_len_basic() {
        let mid = 0;
        let len = 5;
        let iv = IsizeCO::saturating_from_midpoint_len(mid, len).unwrap();
        assert_eq!(iv.len(), len);
        assert_eq!(iv.midpoint(), mid);

        assert!(IsizeCO::saturating_from_midpoint_len(mid, 0).is_none());

        let iv = IsizeCO::saturating_from_midpoint_len(isize::MIN, 10).unwrap();
        assert!(iv.start() >= isize::MIN);

        let iv = IsizeCO::saturating_from_midpoint_len(isize::MAX, 10).unwrap();
        assert!(iv.end_excl() <= isize::MAX);
    }
}

mod prop_tests {
    use proptest::prelude::*;

    use super::*;

    fn mixed_scalar() -> impl Strategy<Value = isize> {
        prop_oneof![3 => prop::sample::select(&[isize::MIN, isize::MAX, 0, -1, 1]), 7 => any::<isize>()]
    }

    proptest! {
        #[test]
        fn prop_midpoint_in_bounds(start in any::<isize>(), end in any::<isize>()) {
            if let Some(iv) = IsizeCO::try_new(start, end) {
                let mp = iv.midpoint();
                prop_assert!(mp >= iv.start());
                prop_assert!(mp <= iv.end_incl());
            }
        }

        #[test]
        fn prop_checked_from_midpoint_len_inverse(mid in mixed_scalar(), len in 1usize..=255) {
            if let Some(iv) = IsizeCO::checked_from_midpoint_len(mid, len) {
                prop_assert_eq!(iv.len(), len);
                prop_assert_eq!(iv.midpoint(), mid);
            }
        }

        #[test]
        fn prop_saturating_from_midpoint_len_safety(mid in mixed_scalar(), len in 1usize..=255) {
            if let Some(iv) = IsizeCO::saturating_from_midpoint_len(mid, len) {
                prop_assert!(iv.start() < iv.end_excl());
                prop_assert_eq!(iv.midpoint(), iv.start() + (iv.len()/2) as isize);
            }
        }
    }
}
