name: CodSpeed

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    uses: jcfangc/ci/.github/workflows/rust-codspeed.yml@v0
    with:
      rust_toolchain: stable
      build_command: cargo codspeed build -m simulation --features "stack,parallel"
      run_command: cargo codspeed run -m simulation "ours_"
